version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/output:/app/output
      - ./backend/recordings:/app/recordings
      - ./backend/reports:/app/reports
    environment:
      - YOLO_MODEL_PATH=./models/yolov8n.pt
      - CONF_THRESHOLD=0.4
      - YAW_T=20
      - PITCH_T=15
      - STREAM_WIDTH=1280
      - STREAM_HEIGHT=720
      - STREAM_FPS=20
      - FLASK_ENV=production
      - FLASK_DEBUG=False
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: attention-detector-network

